#!/bin/bash
echo -n "DEPLOY? Think hard before typing 'yes' or 'no' [ENTER]: "
read yesNo
if  [ $yesNo == "no" ]; then
    echo "Cancelled."
    exit 0
else
    LambdaRoot="/home/ec2-user/environment/Lambda"
    bucketName="io.chedda.lambda"
    echo "Deploy Paths:"
    find $LambdaRoot -path '*/index.js' -type f -not -path '*node_modules*' | 
        while read pathName; do 
            echo $pathName
            
            sourceDir=${pathName%'/index.js'} #strips the /index.js off the end
            echo sourceDir
            
            cd $sourceDir

            lambdaName=$(basename $sourceDir)
            echo $lambdaName

            s3Path="s3://$bucketName/$lambdaName.zip"
            echo $s3Path
            
            zip -rq - ./* | aws s3 cp - $s3Path
            echo "Zipped to S3"

            # aws lambda update-function-code --function-name $lambdaName --s3-bucket $bucketName --s3-key "$lambdaName.zip"
            echo "Function code updated: $lambdaName"
            
            cd -
    done
    echo "Done."
    exit 0
fi