#!/bin/bash
git status
echo -n "SPREAD PLAID AROUND? Think hard before typing 'yesplaid' or 'no' [ENTER]: "
read yesNo
if  [ $yesNo == "yesplaid" ]; then
    LambdaRoot="/home/ec2-user/environment/Lambda"
    srcPath="$LambdaRoot/!QLibs/QuantaPlaid"
    echo "Source path = $srcPath"
    echo "Target Dirs:"
    find $LambdaRoot -path '*/QuantaPlaid' -type d -not -path '*/!QLibs*' | 
        while read dirName; do 
            # echo $dirName
        
            rm -rf $dirName # smash the old version
            mkdir $dirName # create a new target directory

            targetDir=${dirName%QuantaPlaid} #strips the QuantaLib directory off the end to make it put QL in the right place
            echo $targetDir
            
            cp -rfu $srcPath $targetDir # Copy in the updated QuantaPlaid files
    done
    echo "Done."
    exit 0
else
    echo "Cancelled."
    exit 0
fi
